curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=A" > fr_A.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=B" > fr_B.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=C" > fr_C.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=D" > fr_D.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=Oui" > fr_Oui.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=Non" > fr_Non.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=E" > fr_E.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=F" > fr_F.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=G" > fr_G.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=H" > fr_H.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=Effacer" > fr_Effacer.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=Parler" > fr_Parler.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=I" > fr_I.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=J" > fr_J.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=K" > fr_K.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=L" > fr_L.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=M" > fr_M.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=N" > fr_N.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=O" > fr_O.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=P" > fr_P.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=Q" > fr_Q.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=R" > fr_R.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=S" > fr_S.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=T" > fr_T.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=U" > fr_U.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=V" > fr_V.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=W" > fr_W.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=X" > fr_X.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=Y" > fr_Y.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=Z" > fr_Z.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=espace" > fr_espace.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=succion" > fr_succion.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=avide" > fr_avide.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=froid" > fr_froid.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=position" > fr_position.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=bassin" > fr_bassin.mp3
