curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=qu" > fr_qu.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=besoins" > fr_besoins.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=succion" > fr_succion.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=I+need+suction" > en_I+need+suction.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=position" > fr_position.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=I+need+to+change+position" > en_I+need+to+change+position.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=bassin" > fr_bassin.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=I+need+the+bed+pan" > en_I+need+the+bed+pan.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=suivant" > fr_suivant.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=sentir" > fr_sentir.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=avide" > fr_avide.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=I+am+hungry" > en_I+am+hungry.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=suivant" > fr_suivant.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=I+am+cold" > en_I+am+cold.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=I+am+hot" > en_I+am+hot.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=chaud" > fr_chaud.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=premiere" > fr_premiere.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=quatrieme" > fr_quatrieme.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=troisieme" > fr_troisieme.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=fr&q=deuxieme" > fr_deuxieme.mp3
