curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=A" > en_A.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=B" > en_B.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=C" > en_C.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=D" > en_D.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=Oui" > en_Oui.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=Non" > en_Non.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=E" > en_E.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=F" > en_F.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=G" > en_G.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=H" > en_H.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=Effacer" > en_Effacer.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=Parler" > en_Parler.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=I" > en_I.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=J" > en_J.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=K" > en_K.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=L" > en_L.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=M" > en_M.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=N" > en_N.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=O" > en_O.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=P" > en_P.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=Q" > en_Q.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=R" > en_R.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=S" > en_S.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=T" > en_T.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=U" > en_U.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=V" > en_V.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=W" > en_W.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=X" > en_X.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=Y" > en_Y.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=Z" > en_Z.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=espace" > en_espace.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=succion" > en_succion.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=avide" > en_avide.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=froid" > en_froid.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=position" > en_position.mp3
curl -A "Mozilla" "http://translate.google.com/translate_tts?tl=en&q=bassin" > en_bassin.mp3
